/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'As you gain more fans, more options will unlock. Try to get 100 fans to begin with.': '随着您获得更多粉丝，更多选项将会解锁。 尝试从获得100位粉丝开始。',
    'Changelog': '更新日志',
    'Confirm': '确认',
    'Duration': '持续时间',
    'Flip': '翻转',
    'Format Numbers': '数字格式',
    'Glossary': '词汇表',
    'Hello World': '你好，世界',
    'Info': '信息',
    'Inspiration': '灵感',
    'Lock Idols': '锁定偶像',
    'Leave Feedback': '留下反馈',
    'Save Automatically': '自动保存',
    'Send': '发送',
    'Run In Background': '在后台运行',
    'Unlock': '解锁',
    'Upgrade Cost': '升级成本',
    'Upgrade Description': '升级持续时间',
    'Upgrade Flavour Text': '升级趣味文字',
    'Wardrobe': '衣柜',
    'Value': '值',
    'Visible': '可见',
    'Sugar Coating': '糖衣',
    'Slime Idol': '史莱姆偶像',
    'Singsong Idol': '歌唱偶像',
    'Candy Idol': '糖果偶像',
    'Cameo Idol': '客串偶像',
    'Pretty Idol': '漂亮偶像',
    'Catgirl Idol': '猫女偶像',
    'Show Symbols': '显示符号',
    'Show Additional Data': '显示其他数据',
    'Reset Game': '重置游戏',
    'Player Particles': '玩家粒子',
    'Cancel': '取消',
    'How to Play': '怎么玩',
    'Simple Dancing': '简单舞蹈',
    'Simple Particles': '简单粒子',
    'Upgrade Name': '升级名称',
    'Upgrades': '升级',
    'Idol Particles': '偶像粒子',
    'Show Debug Info': '显示调试信息',
    'This game is no longer receiving updates.': '这个游戏不再进行更新。',
    'Options': '选项',
    'Name': '名称',
    'Letters': '字母',
    'Label': '标签',
    "Idol": "偶像",
    'ERROR': '错误',
    'Debug': '调试',
    'Data': '数据',
    'Ben Davis': '我是戴维斯',
    'Classic': '经典',
    'Blue': '蓝色',
    'Inspiration Module': '灵感模块',
    'Custom Wallpaper': '自定义壁纸',
    'Extra Bounce': '额外弹跳',
    'Feline Fashion': '猫时装',
    'Forced Blush': '强制腮红',
    'Raglan': '插肩',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'The outfit that she wore on the day she entered the office. Her everyday clothes, actually. Known for the ability to make any person seem younger than they are.': '她进入办公室那天穿的衣服。 实际上，她每天的衣服。 以使任何人看起来都比他们年轻的能力而闻名。',
    'Ilise Rose\nCosplay, Outfit, Hyper\n\nA hyperactive, befreckled newcomer to the idol scene. Known for her cosplay hobby, she makes a lot of friends (and a few enemies) by paying tribute to their outfits. Her followers tend to treat her like a child because of her innocent appearance which she takes advantage of at every opportunity.\n\n??? (Unlocks at level 25)\n\nLikes: ??? (Unlocks at level 50)\n\nDislikes: ??? (Unlocks at level 50': '伊莉斯·罗斯cosplay, 套装, 超级\n\n一个极度活跃，长着雀斑的新人进入偶像圈。她的cosplay爱好让她结交了很多朋友(也有一些敌人)。她的追随者往往把她当作一个孩子，因为她的天真的外表，她利用每一个机会。(在25级解锁)\n\n喜欢:??(50级解锁)\n\n不喜欢: ??(在50级时解锁',
    'Slime\nGoo\n\nAn exceptionally good looking slime who managed to get work based on her incredibly good looks. With no ability to sing, her success is largely based around her bouncy personality. Always cheerful and accepting of fans curious of her texture, her supporters are never far away with extra water in case she gets a little dried up. She can change her shape at will, but doesn\'t do so often.\n\nOriginally a feral slime roaming the Slime Plains, a hero came along and saw her for beauty rather than her experience points. He offered her a better life and eventually she worked her way up the social ladder to stardom.\n\nLikes: ??? (Unlocks at level 50)\n\nDislikes: ??? (Unlocks at level 50': '史莱姆\n粘性物\n\n一只特别好看的史莱姆谁设法得到工作基于她难以置信的好容貌。虽然她不会唱歌，但她的成功很大程度上是基于她活泼的个性。粉丝们对她的身姿感到好奇，她的支持者们总是很乐意接受，并随时为她补充水分，以防她的身体干枯。她可以随意改变她的形状，但不经常这样做。最初是一个野性的黏液漫游在黏液平原，一个英雄来了，看到她的美丽而不是她的经验点。他给她提供了更好的生活，最终她在社会阶梯上一步步爬上了明星的位置。\n\n喜欢: ? ?(50级解锁)\n\n不喜欢: ??(在50级时解锁',
    'The default sprite. It looks more beautiful than any other slime for some reason.': '默认的精灵。 由于某种原因，它看起来比其他任何史莱姆都要漂亮。',
    'Wink': '眨眼',
    'Unlocked': '已解锁',
    '\"The power to blush on call is great for fan meetups.\"': '“在电话中脸红的能力非常适合粉丝聚会。”',
    '\"Without limbs or a voice, this is about as much interaction a fan can ask for!\"': '“没有四肢和声音，这是一个粉丝可以要求的最多的互动!\”',
    '\"Playing basketball with the fans. As the ball.\"': '“和粉丝们一起打篮球。球。”',
    '\"It\'s just her, though.\"': '“不过，就是她。”',
    'Light, thin, and hugs every curve. Her standard performance outfit.': '轻，薄，拥抱每一个曲线。她的标准表演服装。',
    'The default theme. It includes pieces that reference common user interface terminology and icongraphy.': '默认主题。 它包括参考通用用户界面术语和图标的部分。',
    'This outfit has not been unlocked.': '这件衣服尚未解锁。',
    'Unlock a new outfit for the wardrobe': '解锁衣柜的新装',
    'Sugar Sweet Cutie': '甜心小可爱',
    'Gain 1 Inspiration for every user performance': '为每个用户的表现获得1个灵感',
    'Her standard performance wear. Most fans believe this is her key look and think no outfit she wears will better suit her.': '她的标准表演服。 大多数粉丝认为这是她的关键外观，并认为她穿的衣服不会比她更适合她。',
    'Boing Boing': 'Boing Boing',
    'Cynthia\nApple, Red, Siren\n\nA very professional idol. She takes her work seriously and has by far the best voice in the industry. Any time she spends not performing is spent doing vocal training exercises and writing new songs. She is her own toughest critique and struggles with insecurity, but pays a lot of attention to what the fans want.\n\n??? (Unlocks at level 25)\n\nLikes: ??? (Unlocks at level 50)\n\nDislikes: ??? (Unlocks at level 50': '辛西娅\n苹果, 红色, 塞壬\n一个非常专业的偶像。她认真对待自己的工作，拥有目前为止业内最好的声音。她把不表演的时间都花在声乐训练和写新歌上了。她是她自己最严厉的批评和斗争的不安全感，但关注粉丝想要什么。(在25级解锁)\n\n喜欢:??(50级解锁)\n\n不喜欢: ??(在50级时解锁',
    'A variation on the default theme. Comes pre-packaged with enterprise editions of the operating system.': '默认主题的变体。 预先包装了企业版的操作系统。',
    'Click (almost) anywhere on the screen to perform. Performances gain fans. Every 100 performances increases your base fan gain.': '单击（几乎）在屏幕上的任意位置进行游戏。 表演可以赢得粉丝。 每100场演出将增加您的基础粉丝人数。',
    'Feedback is completely anonymous and not tied to your save file, your ip address, or any previous telemetry.\n\nFeel free to leave comments, criticisms, suggestions, bug reports, links to fanart, memes, or whatever.': '反馈完全是匿名的，与您的存档文件，IP地址或任何以前的遥测技术无关。\n \n请随时发表评论，批评，建议，错误报告，与粉丝，模因的链接等。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "Formatting Precision:": "格式精度：",
    "Formatting Type: ": "格式类型：",
    "Frame Length Modifier: ": "帧长修改器：",
    "Scale: ": "比例: ",
    "Beat Offset: ": "节拍偏移：",
    "Beat Rate: ": "节拍率：",
    "BPM: ": "BPM: ",
    "Idol Scale: ": "偶像比例: ",
    "idol clicker v": "偶像点击 v",
    "Clicker Idol": "点击偶像",
    "Image Change: ": "图像变化：",
    "Encore: ": "再来一次：",
    "Unlock with ": "解锁需要 ",
    "Level ": "等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Fan - A fan. idol clicker's main currency.": "粉丝 - 一个粉丝。 偶像点击的主要货币。",
    "": "",
    "Inspiration Level - The level of inspiration. Every level of inspiration increases Idol performance rate, encore chance, worth share, and fan gain.": "灵感等级 - 灵感的等级。每一级灵感增加偶像的表现率，再来一次几率，价值分享，和粉丝增益。",
    "Worth Share - The percentage of an Idol's fan gain per performance that the user gains per user performance.": "价值分享 - 一个偶像的粉丝获得的百分比，每用户获得的每用户性能。",
    "Encore - An extra performance performed automatically at the end of a performance.": "再来一次 - 在一次表演结束时自动执行的额外表演。",
    "Performance - An action that gains fans.": "表现——获得粉丝的行为。",
    "Soul Link - The percentage increase of an Idol's fan gain per performance per 100 user performances.": "灵魂链接 - 每100个用户的表现增加一个偶像的粉丝的百分比。",
    "Astonishment - The percent chance to perform astonishingly. Astonishing performances gain significantly more fans.": "惊人 - 惊人表现的几率百分比。 惊人的表演吸引了更多的粉丝。",
    "Level - A level. Raising an Idol's level requires fans. Higher level Idol's earn more fans. Leveling up can unlock upgrades.": "级别 - 等级。 提高偶像的等级需要粉丝。 较高级别的偶像可以赢得更多粉丝。 升级可以解锁升级。",
    "Total Supervision Time - The time passed while the game is running.": "总监控时间 - 在游戏运行时经过的时间。",
    "Total Career Time - The time passed since the career started until this moment.": "职业生涯总时间 - 从职业生涯开始到现在为止所经过的时间。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^([\d\.,]+)\n([\d\.,]+)\n([\d\.,]+)$/,
    /^([\d\.,]+)\n([\d\.,]+)\nNaN$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\n([\d\.,]+)\n([\d\.,]+)\n([\d\.,]+)\n(.+)\n(.+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, 'aaa'],
    [/^Pretty Idol\n(.+) \n(.+) \/\n(.+) \/$/, '漂亮偶像\n$1 \n$2\/\n$3\/'],
    [/^Slime Idol\n(.+) \n(.+) \/\n(.+) \/$/, '史莱姆偶像\n$1 \n$2\/\n$3\/'],
    [/^Singsong Idol\n(.+) \n(.+) \/\n(.+) \/$/, '歌唱偶像\n$1 \n$2\/\n$3\/'],
    [/^Candy Idol\n(.+) \n(.+) \/\n(.+) \/$/, '糖果偶像\n$1 \n$2\/\n$3\/'],
    [/^Catgirl Idol\n(.+) \n(.+) \/\n(.+) \/$/, '猫女偶像\n$1 \n$2\/\n$3\/'],
    [/^Cameo Idol\n(.+) \n(.+) \/\n(.+) \/$/, '客串偶像\n$1 \n$2\/\n$3\/'],
    [/^Gain (.+)\% $/, '获得 $1\% '],
    [/^Gain (.+)x more \/$/, '获得 $1x 的 \/'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);